export const pricingContent = {
  en: {
    eyebrow: "Architecture engagements", title: "Invest in a system—not an isolated deliverable.", subtitle: "Clear starting points help organizations plan confidently. Discovery determines the right scope, sequence, and long-term path.", principleLabel: "What pricing represents", principle: "Strategy, communication, design, technology, measurement, and launch support organized around a useful business outcome.", starting: "Starting at", cta: "Schedule a Strategic Review", deliverablesLabel: "Typical deliverables", addonsLabel: "Optional additions", note: "Starting prices establish a planning baseline. Final proposals reflect scope, content readiness, integrations, automation, research, creative production, and reporting needs.",
    plans: {
      launch: { title: "Launch Architecture", price: "$1,500", bestForLabel: "Best for emerging organizations", purpose: "A professionally designed digital foundation that establishes credibility and creates a clear path for inquiries.", audiences: ["Nonprofits", "Small businesses", "Community organizations", "Churches", "New businesses", "Professional practices"], deliverables: ["Discovery consultation", "Website strategy", "Up to 5 professionally designed pages", "Mobile optimization", "Brand-aligned design", "Basic SEO foundations", "Contact forms", "Analytics setup", "Google indexing guidance", "Accessibility review", "Performance optimization", "Basic CMS training", "Launch support"], addons: ["Photography enhancement", "Additional pages", "Copywriting", "Blog", "Translation", "Booking integration"] },
      growth: { title: "Growth Architecture", price: "$3,000", bestForLabel: "Best for scaling organizations", purpose: "A scalable marketing foundation that connects conversion paths, content, customer information, and performance evidence.", audiences: ["Growing businesses", "Hospitality", "Professional services", "Healthcare", "Preparedness", "Community organizations"], deliverables: ["Everything in Launch Architecture", "Expanded website", "Conversion optimization", "Landing pages", "CRM integration", "Email capture", "Analytics dashboard", "Campaign planning", "SEO improvements", "Content architecture", "Blog framework", "Service funnels", "Performance reporting", "Technical optimization"] },
      commerce: { title: "Commerce Architecture", price: "$5,000", bestForLabel: "Best for transactional organizations", purpose: "A connected commerce experience for products, memberships, registrations, or online services—built around confident customer decisions.", audiences: ["Product businesses", "Memberships", "Events", "Registrations", "Online services"], deliverables: ["Everything in Growth Architecture", "E-commerce implementation", "Payment integration", "Inventory support", "Product architecture", "Customer journey optimization", "Checkout optimization", "Customer account setup", "Advanced analytics", "Technical integrations", "Security review", "Commerce reporting"] }
    },
    services: { eyebrow: "Custom-scope capabilities", title: "Strategic Services", subtitle: "Focused services can stand alone or connect to a larger architecture engagement. Each is quoted according to the problem, evidence, and execution required.", scope: "Quoted by scope", items: {
      digital: { title: "Digital Architecture", outcome: "Create a clearer path from discovery to action.", items: ["Websites", "Information architecture", "User experience", "Landing pages", "Conversion systems"] },
      creative: { title: "Creative Production", outcome: "Turn complex ideas into useful, credible media.", items: ["Commercials and video", "Photography enhancement", "Social and motion graphics", "Presentations and infographics", "Brand storytelling", "Mission and capability statements", "Proposal and campaign assets"] },
      marketing: { title: "Marketing Intelligence", outcome: "Know what to create, for whom, and why.", items: ["Market and competitor research", "Audience research", "Campaign strategy", "Content planning", "SEO research", "Trend monitoring", "Advertising strategy"] },
      business: { title: "Business Intelligence", outcome: "Turn operating activity into decision-ready evidence.", items: ["Power BI", "Executive dashboards", "Reporting and analytics", "Marketing performance", "Data visualization", "Python automation", "Decision support"] },
      automation: { title: "Automation", outcome: "Reduce repetitive work without losing control.", items: ["Microsoft automation", "Scheduling", "CRM workflows", "Appointment systems", "Virtual receptionist", "Lead routing", "Knowledge systems", "Workflow optimization"] },
      ai: { title: "AI Enablement", outcome: "Use AI where it improves quality, speed, or clarity.", items: ["Human-guided implementation", "Content assistance", "Knowledge systems", "Translation workflows", "Content repurposing", "Research assistance", "Internal AI workflows"] }
    } },
    partnerships: { eyebrow: "After launch", title: "Ongoing Growth Partnerships", subtitle: "Digital systems improve through attention, evidence, and iteration. Partnership scopes are shaped around the support an organization actually needs.", note: "Custom proposals are developed based on organizational goals and scope.", items: {
      essential: { title: "Essential Partnership", purpose: "Keep the digital foundation healthy, current, and visible.", items: ["Website maintenance", "Security updates", "Monthly reporting", "Content updates", "Minor improvements"] },
      growth: { title: "Growth Partnership", purpose: "Improve visibility and campaign readiness over time.", items: ["Everything in Essential", "Content support", "SEO improvements", "Campaign planning", "Monthly strategy meeting", "Performance review"] },
      strategic: { title: "Strategic Partnership", purpose: "Connect intelligence, production, automation, and executive decisions.", items: ["Everything in Growth", "Marketing intelligence", "Creative production", "Analytics", "Automation", "Priority support", "Quarterly planning", "Executive reporting"] }
    } },
    discovery: { eyebrow: "A disciplined beginning", title: "Every Project Begins With Discovery", subtitle: "No two organizations share the same mission, audience, constraints, or opportunities. We understand those realities before recommending the system.", steps: ["Discovery", "Research", "Architecture", "Proposal", "Build", "Launch", "Measure", "Improve"] },
    faq: { eyebrow: "Pricing FAQ", title: "Useful answers before the first conversation.", items: [
      { q: "Why are prices listed as starting at?", a: "The starting price reflects a defined baseline. Content readiness, integrations, research, automation, and reporting requirements determine the final scope." },
      { q: "Do nonprofits receive customized proposals?", a: "Yes. Proposals can reflect mission priorities, operational realities, phased work, and appropriate project scope." },
      { q: "Can projects be completed in phases?", a: "Yes. A phased roadmap can protect the most important outcome while spreading implementation across practical stages." },
      { q: "Can an existing website be improved instead of rebuilt?", a: "Yes. Discovery may show that focused improvements to structure, messaging, performance, or integrations are more useful than replacement." },
      { q: "Can VTHREE work with internal marketing teams?", a: "Yes. VTHREE can provide architecture, technical execution, research, creative support, or reporting alongside an internal team." },
      { q: "Do you offer ongoing support?", a: "Yes. Ongoing partnerships can cover maintenance, campaigns, content, analytics, automation, planning, and iterative improvement." },
      { q: "Can you improve photography or existing content?", a: "Yes. Existing visual and written assets can often be enhanced, reorganized, localized, or repurposed before new production is recommended." },
      { q: "Can VTHREE create presentations, campaigns, and training materials?", a: "Yes. Strategic communications and creative production can support presentations, campaigns, proposals, capability statements, and training resources." },
      { q: "Do you provide analytics after launch?", a: "Yes. Analytics foundations, dashboards, reporting, and decision recommendations can be included in the initial scope or an ongoing partnership." }
    ] },
    scheduling: { eyebrow: "Start with context", title: "Let’s discuss your goals.", copy: "Every engagement begins with understanding your organization, audience, and objectives. Schedule a strategic review to explore a system designed for long-term growth.", cta: "Request a Strategic Review", placeholderLabel: "Microsoft Bookings integration placeholder", placeholderTitle: "Microsoft Bookings", placeholderNote: "Scheduling integration reserved. The final embed will fit this container without changing the page layout." },
    trust: { eyebrow: "How VTHREE works", title: "Built for confidence before, during, and after launch.", items: ["Research-driven process", "Transparent communication", "Accessibility-conscious development", "Performance-focused implementation", "Long-term partnerships", "Scalable solutions", "Human-guided AI", "Evidence-based recommendations", "Measured outcomes"] },
    finalCta: { copy: "The right engagement begins with a clear understanding of the outcome.", cta: "Let’s Design Your Digital Growth System" }
  },
  es: {
    eyebrow: "Servicios de arquitectura", title: "Invierta en un sistema, no en un entregable aislado.", subtitle: "Los puntos de partida claros ayudan a planificar con confianza. El descubrimiento determina el alcance, la secuencia y la ruta a largo plazo.", principleLabel: "Qué representa el precio", principle: "Estrategia, comunicación, diseño, tecnología, medición y apoyo de lanzamiento organizados alrededor de un resultado útil.", starting: "Desde", cta: "Programar una Revisión Estratégica", deliverablesLabel: "Entregables típicos", addonsLabel: "Opciones adicionales", note: "Los precios iniciales establecen una base de planificación. La propuesta final refleja alcance, contenido, integraciones, automatización, investigación, producción creativa e informes.",
    plans: {
      launch: { title: "Arquitectura de Lanzamiento", price: "$1,500", bestForLabel: "Para organizaciones emergentes", purpose: "Una base digital profesional que establece credibilidad y crea una ruta clara para consultas.", audiences: ["Organizaciones sin fines de lucro", "Pequeñas empresas", "Organizaciones comunitarias", "Iglesias", "Empresas nuevas", "Prácticas profesionales"], deliverables: ["Consulta de descubrimiento", "Estrategia web", "Hasta 5 páginas diseñadas profesionalmente", "Optimización móvil", "Diseño alineado con la marca", "Fundamentos de SEO", "Formularios de contacto", "Configuración de analítica", "Orientación para indexación en Google", "Revisión de accesibilidad", "Optimización de rendimiento", "Capacitación básica de CMS", "Apoyo de lanzamiento"], addons: ["Mejora de fotografía", "Páginas adicionales", "Redacción", "Blog", "Traducción", "Integración de reservas"] },
      growth: { title: "Arquitectura de Crecimiento", price: "$3,000", bestForLabel: "Para organizaciones en crecimiento", purpose: "Una base de marketing escalable que conecta conversiones, contenido, información del cliente y evidencia de rendimiento.", audiences: ["Empresas en crecimiento", "Hospitalidad", "Servicios profesionales", "Salud", "Preparación", "Organizaciones comunitarias"], deliverables: ["Todo en Arquitectura de Lanzamiento", "Sitio web ampliado", "Optimización de conversión", "Landing pages", "Integración CRM", "Captura de correo", "Panel de analítica", "Planificación de campañas", "Mejoras de SEO", "Arquitectura de contenido", "Estructura de blog", "Embudos de servicios", "Informes de rendimiento", "Optimización técnica"] },
      commerce: { title: "Arquitectura de Comercio", price: "$5,000", bestForLabel: "Para organizaciones transaccionales", purpose: "Una experiencia comercial conectada para productos, membresías, registros o servicios en línea.", audiences: ["Productos", "Membresías", "Eventos", "Registros", "Servicios en línea"], deliverables: ["Todo en Arquitectura de Crecimiento", "Implementación de comercio electrónico", "Integración de pagos", "Apoyo de inventario", "Arquitectura de productos", "Optimización del recorrido", "Optimización del pago", "Cuentas de clientes", "Analítica avanzada", "Integraciones técnicas", "Revisión de seguridad", "Informes comerciales"] }
    },
    services: { eyebrow: "Capacidades con alcance personalizado", title: "Servicios Estratégicos", subtitle: "Los servicios pueden funcionar solos o conectarse a una arquitectura mayor. Se cotizan según el problema, la evidencia y la ejecución requerida.", scope: "Cotizado por alcance", items: {
      digital: { title: "Arquitectura Digital", outcome: "Crear una ruta más clara desde el descubrimiento hasta la acción.", items: ["Sitios web", "Arquitectura de información", "Experiencia del usuario", "Landing pages", "Sistemas de conversión"] },
      creative: { title: "Producción Creativa", outcome: "Convertir ideas complejas en medios útiles y creíbles.", items: ["Comerciales y video", "Mejora de fotografía", "Redes y motion graphics", "Presentaciones e infografías", "Narrativa de marca", "Misión y capacidad", "Recursos para propuestas y campañas"] },
      marketing: { title: "Inteligencia de Marketing", outcome: "Saber qué crear, para quién y por qué.", items: ["Investigación de mercado y competencia", "Investigación de audiencia", "Estrategia de campaña", "Planificación de contenido", "Investigación SEO", "Monitoreo de tendencias", "Estrategia publicitaria"] },
      business: { title: "Inteligencia Empresarial", outcome: "Convertir actividad operativa en evidencia para decisiones.", items: ["Power BI", "Paneles ejecutivos", "Informes y analítica", "Rendimiento de marketing", "Visualización de datos", "Automatización con Python", "Apoyo a decisiones"] },
      automation: { title: "Automatización", outcome: "Reducir el trabajo repetitivo sin perder el control.", items: ["Automatización de Microsoft", "Programación", "Flujos CRM", "Sistemas de citas", "Recepcionista virtual", "Rutas de prospectos", "Sistemas de conocimiento", "Optimización de flujos"] },
      ai: { title: "Habilitación de IA", outcome: "Usar IA donde mejora calidad, velocidad o claridad.", items: ["Implementación guiada por personas", "Asistencia de contenido", "Sistemas de conocimiento", "Flujos de traducción", "Reutilización de contenido", "Asistencia de investigación", "Flujos internos de IA"] }
    } },
    partnerships: { eyebrow: "Después del lanzamiento", title: "Alianzas de Crecimiento Continuo", subtitle: "Los sistemas digitales mejoran con atención, evidencia e iteración. El alcance se adapta al apoyo que la organización realmente necesita.", note: "Las propuestas personalizadas se desarrollan según los objetivos y el alcance de la organización.", items: {
      essential: { title: "Alianza Esencial", purpose: "Mantener la base digital saludable, actualizada y visible.", items: ["Mantenimiento web", "Actualizaciones de seguridad", "Informes mensuales", "Actualizaciones de contenido", "Mejoras menores"] },
      growth: { title: "Alianza de Crecimiento", purpose: "Mejorar la visibilidad y preparación de campañas con el tiempo.", items: ["Todo en Esencial", "Apoyo de contenido", "Mejoras de SEO", "Planificación de campañas", "Reunión estratégica mensual", "Revisión de rendimiento"] },
      strategic: { title: "Alianza Estratégica", purpose: "Conectar inteligencia, producción, automatización y decisiones ejecutivas.", items: ["Todo en Crecimiento", "Inteligencia de marketing", "Producción creativa", "Analítica", "Automatización", "Apoyo prioritario", "Planificación trimestral", "Informes ejecutivos"] }
    } },
    discovery: { eyebrow: "Un comienzo disciplinado", title: "Cada Proyecto Comienza Con Descubrimiento", subtitle: "Ninguna organización comparte la misma misión, audiencia, límites u oportunidades. Comprendemos esas realidades antes de recomendar el sistema.", steps: ["Descubrimiento", "Investigación", "Arquitectura", "Propuesta", "Construcción", "Lanzamiento", "Medición", "Mejora"] },
    faq: { eyebrow: "Preguntas de precios", title: "Respuestas útiles antes de la primera conversación.", items: [
      { q: "¿Por qué los precios dicen ‘desde’?", a: "El precio inicial refleja una base definida. El contenido, las integraciones, la investigación, la automatización y los informes determinan el alcance final." },
      { q: "¿Las organizaciones sin fines de lucro reciben propuestas personalizadas?", a: "Sí. Las propuestas pueden reflejar prioridades de misión, realidades operativas, trabajo por fases y un alcance apropiado." },
      { q: "¿Los proyectos pueden completarse por fases?", a: "Sí. Una ruta por fases puede proteger el resultado principal y distribuir la implementación en etapas prácticas." },
      { q: "¿Se puede mejorar un sitio existente en vez de reemplazarlo?", a: "Sí. El descubrimiento puede mostrar que mejoras específicas de estructura, mensajes, rendimiento o integraciones son más útiles." },
      { q: "¿VTHREE puede trabajar con equipos internos de marketing?", a: "Sí. VTHREE puede aportar arquitectura, ejecución técnica, investigación, creatividad o informes junto a un equipo interno." },
      { q: "¿Ofrecen apoyo continuo?", a: "Sí. Las alianzas pueden cubrir mantenimiento, campañas, contenido, analítica, automatización, planificación y mejora iterativa." },
      { q: "¿Pueden mejorar fotografías o contenido existente?", a: "Sí. Los recursos visuales y escritos pueden mejorarse, reorganizarse, localizarse o reutilizarse antes de recomendar nueva producción." },
      { q: "¿VTHREE crea presentaciones, campañas y materiales de capacitación?", a: "Sí. La comunicación estratégica y producción creativa pueden apoyar presentaciones, campañas, propuestas y materiales de capacitación." },
      { q: "¿Proporcionan analítica después del lanzamiento?", a: "Sí. Las bases analíticas, paneles, informes y recomendaciones pueden incluirse en el alcance inicial o una alianza continua." }
    ] },
    scheduling: { eyebrow: "Comenzar con contexto", title: "Hablemos de sus objetivos.", copy: "Cada proyecto comienza comprendiendo su organización, audiencia y objetivos. Programe una revisión estratégica para explorar un sistema diseñado para crecimiento a largo plazo.", cta: "Solicitar Revisión Estratégica", placeholderLabel: "Marcador para integración de Microsoft Bookings", placeholderTitle: "Microsoft Bookings", placeholderNote: "Integración de agenda reservada. El embed final usará este contenedor sin cambiar el diseño." },
    trust: { eyebrow: "Cómo trabaja VTHREE", title: "Diseñado para generar confianza antes, durante y después del lanzamiento.", items: ["Proceso basado en investigación", "Comunicación transparente", "Desarrollo consciente de accesibilidad", "Implementación enfocada en rendimiento", "Alianzas a largo plazo", "Soluciones escalables", "IA guiada por personas", "Recomendaciones basadas en evidencia", "Resultados medidos"] },
    finalCta: { copy: "El proyecto correcto comienza comprendiendo claramente el resultado.", cta: "Diseñemos Su Sistema de Crecimiento Digital" }
  }
};
